export const WARHAMMER_40K_FACTIONS: string[] = [
  'Adepta Sororitas',
  'Adeptus Custodes',
  'Adeptus Mechanicus',
  'Aeldari',
  'Astra Militarum',
  'Black Templars',
  'Blood Angels',
  'Chaos Daemons',
  'Chaos Knights',
  'Chaos Space Marines',
  'Dark Angels',
  'Death Guard',
  'Deathwatch',
  'Drukhari',
  "Emperor's Children",
  'Genestealer Cults',
  'Grey Knights',
  'Imperial Agents',
  'Imperial Fists',
  'Imperial Knights',
  'Iron Hands',
  'Leagues of Votann',
  'Necrons',
  'Orks',
  'Raven Guard',
  'Salamanders',
  'Space Marines',
  'Space Wolves',
  "T'au Empire",
  'Thousand Sons',
  'Tyranids',
  'Ultramarines',
  'White Scars',
  'World Eaters'
];
